export const DECELERATION_THRESHOLD = 2;
export const GLOBAL_SPEED_MULTIPLIER = 4;
export const HERO_REGENERATION_RATE = 0.0005;
export const HEALTHBAR_HEIGHT = 5;
export const HEALTHBAR_BORDER_WIDTH = 2;
export const ENEMY_INVULNERABILITY_TIME = 100;
export const HERO_INVULNERABILITY_TIME = 700;
